spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/spring_reactive
    username: root
    password: root
  flyway:
    url: jdbc:postgresql://localhost:5432/spring_reactive
    user: root
    password: root